### ISSUE TITLE
Documentation - wiki or githubbed documents?

### ISSUE THREAD

**Issue by distractionability** [hmelberg/overdose#3]
How do we best manage the documentation of the model as we proceed? 

We will need to reference and document assumptions (state-transfer probabilities, use-level changes, etc), as well as clarify and explain the code as it is developed.

Alternatives: 
- A bunch of separate md-documents in the file-collection that is githubbed
- the project wiki at github

I tend towards the wiki - as that would make it easier to navigate between the different documentation files. I also suggest we do this early on in the project, while the migration process remains simple.

**Comment by hmelberg** [comment]
wiki
